model:
  dnn: "vgg16"
  transformer: False
  head_num: 12
  block: 12
  batch_size: 4

hardware:
  tile_num: 1344
  macro_num: 12
  array_col: 256
  array_row: 256
  cim_depth: 1
  precision: 8

paths:
  workspace_root: "/home/fufu/Desktop/accelergy-timeloop-infrastructure/cimloop/workspace"
  arch_name: "isaac"
  macro_name: "wan_nature_2022"
  plot_root: "/home/fufu/Desktop/code/src/TriCIM/outputs"

optimization:
  bayes:
    alpha: 0.2
    max_calls: 15
    initial_points: 10
    early_stop_patience: 20
    acquisition_weight: 2
    random_state: 42
